[colors]
[colors.primary]
background = '#1D2121'
foreground = '#F8D1AA'

# Normal colors
[colors.normal]
black = '#000000'
red = '#F8015D'
green = '#D1F85D'
yellow = '#F8D15D'
blue = '#AAAAF8'
magenta = '#F8AAF8'
cyan = '#83F8F8'
white = '#D1F8F8'

# Bright colors
[colors.bright]
black = '#0D1111'
red = '#F85D84'
green = '#5DF85D'
yellow = '#F85D01'
blue = '#7AA2F8'
magenta = '#AA83F8'
cyan = '#0db9d7'
white = '#ffffff'

[colors.selection]
background = '#F8D1AA'

#[font]
#normal = { family = "GoMono Nerd Font Mono", style = "Regular" }
#bold = { family = "GoMono Nerd Font Mono", style = "Bold" }
#italic = { family = "GoMono Nerd Font Mono", style = "Italic" }
#size = 10.5
#offset.y = 3

