accent = "#d1f85d"
cursor = "#d1f85d"
foreground = "#f8d1aa"
background = "#1d2121"
selection_foreground = "#0d0f0f"
selection_background = "#f8d1aa"

color0 = "#0d0f0f"
color1 = "#f8015d"
color2 = "#5df85d"
color3 = "#bad094"
color4 = "#5f87af"
color5 = "#aa83f8"
color6 = "#aad1d1"
color7 = "#f8d1aa"
color8 = "#4e4e52"
color9 = "#f85d84"
color10 = "#b2e878"
color11 = "#eaf4a0"
color12 = "#8bb2d3"
color13 = "#aaaaf8"
color14 = "#d1f8f8"
color15 = "#fedece"
