accent = "#b2e878"
cursor = "#d1f85d"
foreground = "#f8d1aa"
background = "#1d2121"
selection_foreground = "#000000"
selection_background = "#5df85d"

color0 = "#0d0f0f"
color1 = "#f8015d"
color2 = "#bad094"
color3 = "#f8d15d"
color4 = "#5f87af"
color5 = "#f8aaf8"
color6 = "#aad1d1"
color7 = "#f8d1aa"
color8 = "#4e4e52"
color9 = "#f85d84"
color10 = "#5df85d"
color11 = "#fa9903"
color12 = "#8bb2d3"
color13 = "#aa83f8"
color14 = "#83f8f8"
color15 = "#fedece"
